interface PaymentReceiptData {
  workerName: string;
  amount: number;
  paymentType: string;
  paymentDate: string;
  projectName: string;
  phoneNumber?: string;
}

export function generatePaymentReceiptText(data: PaymentReceiptData): string {
  const { workerName, amount, paymentType, paymentDate, projectName } = data;
  
  return `*Coimbatore Builders Payment Receipt* 📧

👤 Worker: ${workerName}
💰 Amount: ₹${amount}
📋 Type: ${paymentType.charAt(0).toUpperCase() + paymentType.slice(1)}
📅 Date: ${new Date(paymentDate).toLocaleDateString('en-IN')}
🏗️ Project: ${projectName}

Thank you for your hard work! 🙏

---
Generated by Coimbatore Builders App`;
}

export function sharePaymentOnWhatsApp(data: PaymentReceiptData) {
  const message = generatePaymentReceiptText(data);
  const encodedMessage = encodeURIComponent(message);
  
  let whatsappUrl: string;
  
  if (data.phoneNumber) {
    // Clean phone number (remove spaces, dashes, etc.)
    const cleanPhone = data.phoneNumber.replace(/\D/g, '');
    // Add country code if not present
    const phoneWithCountryCode = cleanPhone.startsWith('91') ? cleanPhone : `91${cleanPhone}`;
    whatsappUrl = `https://wa.me/${phoneWithCountryCode}?text=${encodedMessage}`;
  } else {
    // Open WhatsApp without specific contact
    whatsappUrl = `https://wa.me/?text=${encodedMessage}`;
  }
  
  // Open WhatsApp
  window.open(whatsappUrl, '_blank');
}

export function isWhatsAppAvailable(): boolean {
  // Check if device supports WhatsApp (mobile devices)
  return /Android|webOS|iPhone|iPad|iPod|BlackBerry|IEMobile|Opera Mini/i.test(navigator.userAgent);
}
